# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyBoltz_Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip numpy==1.16.1 cython git+https://github.com/UTA-REST/ArXe_plus_anything 
        python -m pip install --upgrade setuptools git+https://github.com/UTA-REST/PyGasMix --user
        python -m pip install --upgrade  git+https://github.com/UTA-REST/PyBoltz_Test_Data --user

    - name: Test Build
      run: |
        source setup.sh
        cd examples/
        python Example_PyBoltz_NoWrapper.py
    - name: Run Pytest
      run: |
        cd /
        source setup.sh
        cd test/
        pip install pytest
        pytest
